PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Controllers/ThecocktaildbController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class ThecocktaildbController : Controller
    {
        [HttpGet]
        public ActionResult GetCocktail()
        {
            
            ML.Result resultProducto = new ML.Result();
            resultProducto.Objects = new List<Object>();
            ML.Cocktail cocktail = new ML.Cocktail();
            string s = cocktail.Nombre;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://www.thecocktaildb.com/api/json/");

                var responseTask = client.GetAsync("v1/1/search.php?s=" + s);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Cocktail>();
                    readTask.Wait();


                    foreach (var resultItem in readTask.Result.drinks)
                    {
                        ML.Cocktail resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Cocktail>(resultItem.ToString());
                        resultProducto.Objects.Add(resultItemList);
                        resultItemList.img1 = "https://www.thecocktaildb.com/images/ingredients/" + resultItemList.strIngredient1 + "-Small.png";
                        resultItemList.img2 = "https://www.thecocktaildb.com/images/ingredients/" + resultItemList.strIngredient2 + "-Small.png";
                        resultItemList.img3 = "https://www.thecocktaildb.com/images/ingredients/" + resultItemList.strIngredient3 + "-Small.png";

                    }

                }
            }
           
            cocktail.drinks = resultProducto.Objects;//Mandar a llamar a la vista, mostrar la vista(HTML)
            return View(cocktail);
        }
        [HttpPost]
        public ActionResult GetCocktail(ML.Cocktail cocktail)
        {

            ML.Result resultProducto = new ML.Result();
            resultProducto.Objects = new List<Object>();

            string n = cocktail.Nombre;
            string i = cocktail.Ingrediente;
            if(i == null)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://www.thecocktaildb.com/api/json/");

                    var responseTask = client.GetAsync("v1/1/search.php?s=" + n);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<ML.Cocktail>();
                        readTask.Wait();


                        foreach (var resultItem in readTask.Result.drinks)
                        {
                            ML.Cocktail resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Cocktail>(resultItem.ToString());
                            resultItemList.img1 = "https://www.thecocktaildb.com/images/ingredients/" + resultItemList.strIngredient1 + "-Small.png";
                            resultItemList.img2 = "https://www.thecocktaildb.com/images/ingredients/" + resultItemList.strIngredient2 + "-Small.png";
                            resultItemList.img3 = "https://www.thecocktaildb.com/images/ingredients/" + resultItemList.strIngredient3 + "-Small.png";
                            resultProducto.Objects.Add(resultItemList);
                        }

                    }
                }

            }
            else
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://www.thecocktaildb.com/api/json/");

                    var responseTask = client.GetAsync("v1/1/filter.php?i=" + i);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<ML.Cocktail>();
                        readTask.Wait();


                        foreach (var resultItem in readTask.Result.drinks)
                        {
                            ML.Cocktail resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Cocktail>(resultItem.ToString());
                            
                            resultProducto.Objects.Add(resultItemList);
                        }

                    }
                }

            }

            cocktail.drinks = resultProducto.Objects;
            return View(cocktail);
        }
    }
}

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("The Cocktail", "GetCocktail", "Thecocktaildb")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PL/Views/Thecocktaildb/GetCocktail.cshtml
@model ML.Cocktail
@{
    ViewBag.Title = "GetCocktail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <section>
        <h2>Cocktail</h2>

    </section>

    <hr />
    <div class="container-fluid">

        @using (Html.BeginForm("GetCocktail", "Thecocktaildb", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
               <div class="row">
                <div class="form-group">
                    <div class="col-md-4">
                        @Html.Label("Nombre Cocktail")
                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre", @autocomplete = "off" })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-4">
                        @Html.Label("Ingrediente")
                        @Html.TextBoxFor(model => model.Ingrediente, new { @class = "form-control", @id = "txtIngrediente", @autocomplete = "off" })
                        @Html.ValidationMessageFor(model => model.Ingrediente, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <br />
                    <input type="submit" value="Buscar" class="btn btn-info" />

                </div>

            </div>

        }
      <br />
    </div>
   
       @foreach(ML.Cocktail cocktail in Model.drinks)
       {
           if (cocktail.strIngredient1 == null)
           {
<div class="row">
    <div class="form-group">
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top">
                <img src="@cocktail.strDrinkThumb" width="150px" height="150px" />
                <h5 class="card-title card-header text-center bg-secondary">Nombre: @cocktail.strDrink</h5>
            </div>
        </div>
    </div>
</div>
    }
    else
    {
    <div class="row">
        <div class="col-sm-6">
            <div class="card text-white bg-dark border-success mb-3 border-4 " style="width: 18rem;">
                <img src="@cocktail.strDrinkThumb" width="150px" height="150px" />
                <h5 class="card-title card-header text-center bg-secondary">Nombre: @cocktail.strDrink</h5>
                <div class="card-body">
                    <p class="card-title card-header text-center bg-secondary">Ingredientes:
                     @cocktail.strIngredient1  <img src="@cocktail.img1" width="20px" height="20px">
                     @cocktail.strIngredient2  <img src="@cocktail.img2" width="20px" height="20px">
                     @cocktail.strIngredient3  <img src="@cocktail.img3" width="20px" height="20px">
                     Instrucciones: @cocktail.strInstructions </p>
                </div>
            </div>
        </div>
    </div>
    }
    <br>
    }
</div>